### ISSUE TITLE
the download link is expired.

### ISSUE THREAD

**Issue by lincan1** [laddie132/LW-PT#1]
Sorry to interrupt you that the download link is expired.Could you please resent the link？
作者您好！我是一个计算机研究生二年级的学生，非常感谢您把代码开源，但是下载数据的链接失效了，您能不能再发一次呢？

**Comment by laddie132** [comment]
It has been updated. You can try again.

**Comment by lincan1** [comment]
Thank you very much !!!
非常感谢您！！！

**Comment by lincan1** [comment]
师兄，我可以加下您的微信吗？我也在北京读书，我的微信是17346610392，我的qq是2478591350@qq.com
